function r = board_variants
% Board plugin registration file
% 1. Any registration file with this name on MATLAB path will be picked up
% 2. Registration file returns a cell array pointing to the location of
%    the board plugins
% 3. Board plugin must be a package folder accessible from MATLAB path,
%    and contains a board definition file

%   Copyright 2012-2013 The MathWorks, Inc.

r = { ...
     'AnalogDevices.daq2.zcu102.plugin_rd_rx', ...
     'AnalogDevices.daq2.zcu102.plugin_rd_tx', ...
     'AnalogDevices.daq2.zcu102.plugin_rd_rxtx' ...
     'AnalogDevices.ad9081_fmca_ebz.zcu102.plugin_rd_rx', ...
     'AnalogDevices.ad9081_fmca_ebz.zcu102.plugin_rd_tx', ...
     'AnalogDevices.ad9081_fmca_ebz.zcu102.plugin_rd_rxtx', ...
     'AnalogDevices.ad9739a_fmc.zc706.plugin_rd_tx' ...
    };
end
% LocalWords:  Zynq ZC
