site_name: Analog Devices, Inc. High-Speed Converter Toolbox

theme: 
  name: material
  logo: assets/matlab_white_icon.svg
  palette:
    - scheme: default
      primary: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

nav:
 - Overview: index.md
 - Installation: install.md
 - Simulation Models: models.md
 - Data Streaming: streaming.md
 - HDL Targeting: targeting.md
 - Examples: examples.md
 - Reference API:
    - HDL Reference Designs:
       - fmcomms2: hdlrefdesigns/fmcomms2.md
       - adrv9361z7035: hdlrefdesigns/adrv9361z7035.md
       - adrv9364z7020: hdlrefdesigns/adrv9364z7020.md
       - pluto: hdlrefdesigns/pluto.md
       - adrv9371: hdlrefdesigns/adrv9371.md
       - adrv9002: hdlrefdesigns/adrv9002.md
       - adrv9009: hdlrefdesigns/adrv9009.md
    - Device Interfaces:
       - adi.AD9081.Rx: sysobjects/adi.AD9081.Rx.md
       - adi.AD9081.Tx: sysobjects/adi.AD9081.Tx.md
       - adi.AD9467.Rx: sysobjects/adi.AD9467.Rx.md
       - adi.DAQ2.Rx: sysobjects/adi.DAQ2.Rx.md
       - adi.DAQ2.Tx: sysobjects/adi.DAQ2.Tx.md


extra_css:
   - stylesheets/style.css
   - stylesheets/rd_style.css

extra_javascript:
   - js/sys_objects.js

plugins:
    - search
    - awesome-pages
    - mermaid2
    - inline-svg

markdown_extensions:
    - attr_list
    - md_in_html
    - admonition
    - pymdownx.details
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences:
        # make exceptions to highlighting of code:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:mermaid2.fence_mermaid