function MXFEADCResponse2 = importfile(filename, dataLines)
%IMPORTFILE1 Import data from a text file
%  MXFEADCRESPONSE2 = IMPORTFILE1(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  MXFEADCRESPONSE2 = IMPORTFILE1(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  MXFEADCResponse2 = importfile("MXFE_ADC_Response.csv", [11, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 10-Jul-2020 10:42:56

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [11, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 10);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["VarName1", "CHIP", "txfe", "VarName4", "VarName5", "VarName6", "VarName7", "VarName8", "VarName9", "VarName10"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
MXFEADCResponse2 = readtable(filename, opts);

end