name: Vale
on: push
jobs:
  Vale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.8'
        architecture: x64
    - name: Install dependencies
      run: |
        sudo apt-get install -y python3-pip python3-setuptools
        pip install rst2html
        curl -sfL https://install.goreleaser.com/github.com/ValeLint/vale.sh | sh -s v2.8.0
        export PATH="./bin:$PATH"
        vale -v
        cd .github/doc
        bash scripts/get_styles.sh
        cp styles/GoogleUpdate/* styles/Google/
        cd ../..
    - name: Lint doc
      run: |
        export PATH="./bin:$PATH"
        vale docs
